#!/bin/bash
#demultiplex barcoded reads generated by Nanopore sequencing.
# For qcat installation help: https://github.com/nanoporetech/qcat
cat ./*.fastq | qcat -b ./output
#Barcodes removal 
cat ./*.fastq | qcat -b ./output --trim

#AssembleyAssembly with reference
/.../minimapx-x.xx_x64-linux/minimap2 -a ref.fasta barcode01.fastq > alin.sam
samtools view -bS alin.sam > seq.bam
samtools sort seq.bam -o seq.sorted.bam
samtools index seq.sorted.bam
samtools depth seq.sorted.bam | awk '{sum+=$3} END {print "Average= ", sum/NR}' > seq.average.txt
 
#Open the result with Ugene to check the coverage and save the consensus.
 

